# Just like numpy ...

In [1]:
import tensorflow as tf

# TensorFlow Constants

In [ ]:
# this is our first tensorflow line of code
# 1. its a tensorflow constant !
# welcome to tensorflow land
x = tf.constant(35, name='x')

# Build the computation Graph

In [2]:
y = x + 5

In [3]:
print(y)

Tensor("add:0", shape=(), dtype=int32)


# Run the Computation Graph

In [4]:
with tf.Session() as session:
    print(session.run(y))

40


In [5]:
%matplotlib inline

In [6]:
import matplotlib.image as mpimg

In [7]:
import matplotlib.pyplot as plt

In [8]:
# which image
filename = "ganesha.jpg"

In [21]:
# load image
raw_image_data = mpimg.imread(filename)

In [26]:
# Lord Ganesha was a scribe for Mr. Veda Vyasa
# who was narrating the Mahabharata.
#
# Later today we want to see if GAN's can learn
# the joint distribution over b/w images of Ganesha's
#
# For now, here is how, our god looks like ...
#
# Notice that there are 13 discrete features.

plt.imshow(raw_image_data)

# TensorFlow Variables
### Stepping into TensorFlow-land from Numpy-land

In [11]:
# create a
# 1, tenforflow constant (last time)
# 2. tensorflow variable (now)
x = tf.Variable(raw_image_data, name='x')

In [15]:
# tf.initialize_all_variables() was deprecated recently
model = tf.global_variables_initializer()

In [24]:
with tf.Session() as session:
    # perform a basic operation
    transpose_op = tf.transpose(x, perm=[1, 0, 2])
    session.run(model)
    result = session.run(transpose_op)

In [25]:
# he may not like it, but here is the transpose
plt.imshow(result)

# TensorFlow Placeholders

In [43]:
x = tf.placeholder("float", 3)
# size is optional, but helps

In [44]:
y = x * 2

In [45]:
with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

[ 2.  4.  6.]


# Another Example of a Placeholder

In [46]:
x = tf.placeholder("float", [None, 3])
# size can be multidimensional

In [47]:
y = x * 2

In [48]:
x_data = [[1, 2, 3],
          [4, 5, 6],]

In [50]:
with tf.Session() as session:
    result = session.run(y, feed_dict={x: x_data})
    print(result)

[[  2.   4.   6.]
 [  8.  10.  12.]]
